@startuml

left to right direction

actor Admin
actor User

rectangle "Deadlock France Community Platform" {

    Admin --> (User Authentication)
    Admin --> (2FA Authentication)
    Admin --> (Create Patchnote)
    Admin --> (Edit Patchnote)
    Admin --> (Delete Patchnote)
    Admin --> (View Statistics)
    Admin --> (Modify Settings)
    Admin --> (Access Logs)
    Admin --> (Log Actions)

    User --> (User Authentication)
    User --> (Recover Password)
    User --> (View Patchnotes)
    User --> (Search Patchnotes)
    User --> (Increment Stats)

}

@enduml

Use Case : [http://www.plantuml.com/plantuml/uml/XP3FIiD04CRl-nH3JthenGUGXjQ2e50CUXzc9ydW_e7PYQM8xsuIXK8YyRRixxUpytsxOgZMn-1SuCR0CgYqdO4NPJB9oJaaomgLZv9-pw-5rRbHmDG6Xis1qOTCxt1KJCImpp7sIUm2fu3MP8qR-7GE07xcm7Px3pVZ6AXwwpYP48w_tSwTksFrdx9NHcCueL6Nil52UF1YA_Z0WLVVlmcVeJOqAIPK5lmvUsakKBEPf7R9Ao8k1Pxo7souX6egUc0Jd5fPx-Ugl33b3rOuOIddh7x6fzMloSeSrunAtOhmc4WvSh8f_u3TbtCxJhwFuHi0]