@startuml

left to right direction

actor Admin
actor User

rectangle "Deadlock France" {


    Admin --> (User Authentication)
    Admin --> (2FA Authentication)
    Admin --> (Manage Patchnotes)
    Admin --> (Manage Users and Roles)
    Admin --> (Manage Heroes, Spells, Items)
    Admin --> (View Statistics and Logs)
    Admin --> (Modify Settings)
    
    User --> (User Authentication)
    User --> (View Patchnotes)
    User --> (Search Patchnotes)
    User --> (Support Project)
    User --> (Increment Stats)
    User --> (Recover Password)
}

@enduml

Use Case : [https://www.plantuml.com/plantuml/uml/XPBHIaCn38RlynHXLmxSZGyW6yXme31sqFlGPkTKUvAHPWuHtzrrAiAEHtlH5lxl_zEKp8kJ-RxF09ctZgvegUqSOp8EdbG0ABWQBcAVvEl-KDW0Aa3IPiR93LFC6fvnQII19_W607XS9nVEPjTuKKsus7l7uYbGpPwUCrVBnN_8FGcrZ6loq8awbp6YrYj84d6ZUHoxPLCkbzZiEEVZkNBkX_1ZuWCsJfwAf_0PUwVjBwaQq_OL6tPFygsVjlgUyPyuGsgzGOy_SiDaeViBsEzsQevhqoSEVYwl91ZtB7xgQU3USD0NjcD-AGUrE8LtW3bBh8Fo0G00]